import React, { useEffect, useState } from 'react';
import { AlertCircle, CalendarDays, CheckCircle2, Loader2, Plus, Trash2, X } from 'lucide-react';
import { AnimatePresence, motion } from 'motion/react';
import { saeAgendamentosService } from '../../services/saeAgendamentosService';
import type { SaeAgendamentoCatalogoProfissional, SaeAgendamentoCatalogoServico, SaeAgendamentoResumo, SaeAgendamentoSlotDisponivel, SaeRemarcarAgendamentoPayload, SaeTipoAtendimento } from '../../types/saeAgendamento';

interface Props { aberto:boolean; agendamento:SaeAgendamentoResumo|null; onClose:()=>void; onSalvo:()=>void|Promise<void>; }
interface Linha { idLocal:string; servicoId:string; profissionalId:string; horaInicio:string; horaFim:string; observacao:string; slots:SaeAgendamentoSlotDisponivel[]; carregando:boolean; erro:string|null; }
const TIPOS:SaeTipoAtendimento[]=['AVALIAÇÃO','REAVALIAÇÃO','RETORNO','ROTINA'];
const INPUT='h-11 w-full rounded-xl border border-border-dark bg-slate-900/50 px-3 text-sm text-white outline-none focus:border-primary/50';
const novaLinha=():Linha=>({idLocal:`${Date.now()}-${Math.random()}`,servicoId:'',profissionalId:'',horaInicio:'',horaFim:'',observacao:'',slots:[],carregando:false,erro:null});
const hora=(v?:string|null)=>v?String(v).slice(0,5):'—';
const hoje=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};

export default function RemarcarAgendamentoModal({aberto,agendamento,onClose,onSalvo}:Props){
  const [servicos,setServicos]=useState<SaeAgendamentoCatalogoServico[]>([]);
  const [profissionais,setProfissionais]=useState<SaeAgendamentoCatalogoProfissional[]>([]);
  const [data,setData]=useState('');
  const [tipo,setTipo]=useState<SaeTipoAtendimento>('ROTINA');
  const [observacao,setObservacao]=useState('');
  const [linhas,setLinhas]=useState<Linha[]>([]);
  const [carregando,setCarregando]=useState(false);
  const [salvando,setSalvando]=useState(false);
  const [erro,setErro]=useState<string|null>(null);
  const [sucesso,setSucesso]=useState<string|null>(null);
  const id=agendamento?.id||'';

  const update=(idLocal:string,patch:Partial<Linha>)=>setLinhas(a=>a.map(l=>l.idLocal===idLocal?{...l,...patch}:l));
  const profs=(sid:string)=>profissionais.filter(p=>p.servicoIds.includes(sid));

  useEffect(()=>{ if(!aberto||!agendamento)return; (async()=>{try{setCarregando(true);setErro(null);const cat=await saeAgendamentosService.listarCatalogo();setServicos(cat.servicos||[]);setProfissionais(cat.profissionais||[]);setData(agendamento.data||'');setTipo((agendamento.tipoAtendimento as SaeTipoAtendimento)||'ROTINA');setObservacao(agendamento.observacao||'');setLinhas(agendamento.servicos.length?agendamento.servicos.map(s=>({idLocal:s.id,servicoId:s.servicoId,profissionalId:s.profissionalId||'',horaInicio:s.horaInicio||'',horaFim:s.horaFim||'',observacao:s.observacao||'',slots:[],carregando:false,erro:null})):[novaLinha()]);}catch(e){setErro(e instanceof Error?e.message:'Não foi possível carregar o agendamento.')}finally{setCarregando(false)}})(); },[aberto,agendamento?.id]);

  const carregarSlots=async(l:Linha,target=data)=>{if(!target||!l.servicoId||!l.profissionalId)return;try{update(l.idLocal,{carregando:true,erro:null});const r=await saeAgendamentosService.consultarDisponibilidade(l.profissionalId,l.servicoId,target,id);update(l.idLocal,{carregando:false,slots:r.slots||[],erro:r.slots?.length?null:'Nenhum horário disponível.'});}catch(e){update(l.idLocal,{carregando:false,slots:[],erro:e instanceof Error?e.message:'Falha ao consultar horários.'})}};
  useEffect(()=>{if(!aberto||!data)return;linhas.forEach(l=>{if(l.servicoId&&l.profissionalId)carregarSlots(l,data)});},[data,aberto]);
  const selecionarServico=(l:Linha,v:string)=>update(l.idLocal,{servicoId:v,profissionalId:'',horaInicio:'',horaFim:'',slots:[],erro:null});
  const selecionarProf=(l:Linha,v:string)=>{const n={...l,profissionalId:v,horaInicio:'',horaFim:'',slots:[],erro:null};update(l.idLocal,n);if(data&&v&&l.servicoId)carregarSlots(n,data)};
  const salvar=async()=>{try{if(!data)throw new Error('Informe a nova data.');for(const l of linhas){if(!l.servicoId||!l.profissionalId||!l.horaInicio||!l.horaFim)throw new Error('Preencha serviço, profissional e horário em todos os itens.')}setSalvando(true);setErro(null);const payload:SaeRemarcarAgendamentoPayload={data,tipoAtendimento:tipo,observacao:observacao.trim()||null,servicos:linhas.map(l=>({servicoId:l.servicoId,profissionalId:l.profissionalId,horaInicio:l.horaInicio,horaFim:l.horaFim,observacao:l.observacao.trim()||null}))};await saeAgendamentosService.remarcar(id,payload);setSucesso('Agendamento atualizado com sucesso.');await onSalvo();window.setTimeout(onClose,700)}catch(e){setErro(e instanceof Error?e.message:'Não foi possível remarcar.')}finally{setSalvando(false)}};
  if(!aberto||!agendamento)return null;
  return <AnimatePresence><div className="fixed inset-0 z-[105] flex items-center justify-center p-3 sm:p-5"><motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="absolute inset-0 bg-black/80 backdrop-blur-sm" onClick={()=>!salvando&&onClose()}/><motion.div initial={{opacity:0,y:18,scale:.98}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:18,scale:.98}} className="relative flex max-h-[94vh] w-full max-w-5xl flex-col overflow-hidden rounded-[24px] border border-border-dark bg-card-dark shadow-2xl">
    <header className="flex items-start justify-between gap-4 border-b border-border-dark px-5 py-4 sm:px-6"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-primary">SAE</p><h2 className="mt-1 text-xl font-bold text-white">Remarcar agendamento</h2><p className="mt-1 text-xs text-slate-500">{agendamento.nomeUsuario} • Prontuário {agendamento.prontuario||'—'}</p></div><button type="button" onClick={onClose} className="rounded-xl border border-border-dark p-2 text-slate-400"><X size={18}/></button></header>
    <div className="min-h-0 flex-1 overflow-y-auto p-4 sm:p-6">{erro&&<div className="mb-4 flex gap-2 rounded-xl border border-rose-500/20 bg-rose-500/10 p-3 text-sm text-rose-300"><AlertCircle size={17}/>{erro}</div>}{sucesso&&<div className="mb-4 flex gap-2 rounded-xl border border-emerald-500/20 bg-emerald-500/10 p-3 text-sm text-emerald-300"><CheckCircle2 size={17}/>{sucesso}</div>}
      {carregando?<div className="flex min-h-[260px] items-center justify-center"><Loader2 size={26} className="animate-spin text-primary"/></div>:<div className="space-y-5">
        <section className="rounded-[18px] border border-border-dark bg-slate-900/20 p-4 sm:p-5"><h3 className="text-sm font-bold text-white">1. Dados da remarcação</h3><div className="mt-4 grid gap-4 sm:grid-cols-3"><Field label="Nova data"><input type="date" min={hoje()} value={data} onChange={e=>{setData(e.target.value);setLinhas(a=>a.map(l=>({...l,horaInicio:'',horaFim:'',slots:[]})))}} className={INPUT}/></Field><Field label="Atendimento"><select value={tipo} onChange={e=>setTipo(e.target.value as SaeTipoAtendimento)} className={INPUT}>{TIPOS.map(t=><option key={t}>{t}</option>)}</select></Field><Field label="Observação"><input value={observacao} onChange={e=>setObservacao(e.target.value)} className={INPUT} placeholder="Opcional"/></Field></div></section>
        <section className="rounded-[18px] border border-border-dark bg-slate-900/20 p-4 sm:p-5"><div className="flex items-center justify-between gap-3"><div><h3 className="text-sm font-bold text-white">2. Serviços, profissionais e horários</h3><p className="mt-1 text-xs text-slate-500">O horário atual é ignorado para não bloquear a própria remarcação.</p></div><button type="button" onClick={()=>setLinhas(a=>[...a,novaLinha()])} className="inline-flex items-center gap-2 rounded-xl border border-primary/20 bg-primary/10 px-3 py-2 text-xs font-bold text-primary"><Plus size={14}/>Adicionar serviço</button></div>
          <div className="mt-5 space-y-4">{linhas.map((l,i)=><div key={l.idLocal} className="rounded-2xl border border-border-dark bg-slate-950/20 p-4"><div className="mb-4 flex items-center justify-between"><p className="text-xs font-bold uppercase tracking-[.12em] text-slate-500">Serviço {i+1}</p><button type="button" onClick={()=>setLinhas(a=>a.length===1?[novaLinha()]:a.filter(x=>x.idLocal!==l.idLocal))} className="rounded-lg border border-rose-500/15 bg-rose-500/5 p-2 text-rose-300"><Trash2 size={14}/></button></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Serviço"><select value={l.servicoId} onChange={e=>selecionarServico(l,e.target.value)} className={INPUT}><option value="">Selecione...</option>{servicos.map(s=><option key={s.id} value={s.id}>{s.nome}{s.sigla?` (${s.sigla})`:''}</option>)}</select></Field><Field label="Profissional"><select value={l.profissionalId} disabled={!l.servicoId} onChange={e=>selecionarProf(l,e.target.value)} className={`${INPUT} disabled:opacity-50`}><option value="">Selecione...</option>{profs(l.servicoId).map(p=><option key={p.id} value={p.id}>{p.nome}</option>)}</select></Field></div>
            <div className="mt-4"><div className="mb-2 flex items-center gap-2"><CalendarDays size={14} className="text-primary"/><span className="text-[10px] font-bold uppercase tracking-[.14em] text-slate-500">Horários disponíveis</span>{l.carregando&&<Loader2 size={14} className="animate-spin text-primary"/>}</div>{l.erro?<p className="rounded-xl border border-amber-500/20 bg-amber-500/10 p-3 text-xs text-amber-300">{l.erro}</p>:l.slots.length?<div className="flex flex-wrap gap-2">{l.slots.map(s=>{const ativo=l.horaInicio===s.horaInicio&&l.horaFim===s.horaFim;return <button key={`${s.horaInicio}-${s.horaFim}`} type="button" onClick={()=>update(l.idLocal,{horaInicio:s.horaInicio,horaFim:s.horaFim})} className={`rounded-xl border px-3 py-2 text-xs font-bold transition ${ativo?'border-primary bg-primary text-white':'border-border-dark bg-slate-900/40 text-slate-300 hover:border-primary/30'}`}>{hora(s.horaInicio)}–{hora(s.horaFim)}</button>})}</div>:<p className="text-xs text-slate-500">Escolha a data, serviço e profissional.</p>}</div>
          </div>)}</div>
        </section>
      </div>}
    </div>
    <footer className="flex flex-col-reverse gap-2 border-t border-border-dark px-5 py-4 sm:flex-row sm:justify-end"><button type="button" onClick={onClose} disabled={salvando} className="rounded-xl border border-border-dark px-4 py-2.5 text-sm font-semibold text-slate-300">Voltar</button><button type="button" onClick={salvar} disabled={salvando||carregando} className="inline-flex items-center justify-center gap-2 rounded-xl bg-primary px-5 py-2.5 text-sm font-bold text-white disabled:opacity-50">{salvando&&<Loader2 size={16} className="animate-spin"/>}Salvar remarcação</button></footer>
  </motion.div></div></AnimatePresence>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div><label className="mb-2 block text-[10px] font-bold uppercase tracking-[.14em] text-slate-500">{label}</label>{children}</div>}
